spring:
  datasource:
    url: ${ env:DB_URL }
    username: ${ env:DB_USERNAME }
    password: ${ env:DB_PASSWORD }
  jpa:
    properties:
      javax.persistence:
        validation:
          mode: auto
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


application:
  security:
    jwt:
      secret-key: ${env:JWT_SECRET_KEY}
      expiration: 86400 ${env:JWT_EXPIRATION}

