spring:
  datasource:
    url: jdbc:postgresql://mydbisnstance.czwgec4as9dn.eu-north-1.rds.amazonaws.com:5432/rent-a-car
    username: postgres
    password: test123456789
  jpa:
    properties:
      javax.persistence:
        validation:
          mode: auto
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


application:
  security:
    jwt:
      secret-key: yBjoJCWOA469OxFWqdIFEzSlcdcu9QGVvUhuBP1M/by/5FM+URd6kAnVHpmmr3Enp9iMd3WKX5CA+FnDSIDnQrmS2tZH924yfWPO/3RTySW1TfklBWYHTkO/Sd76denAysmhAILFHxM9/eoOprCObN+f/7icWoax4jo6BuRMiPXreMR72lMDywg3lMch5Az/
      expiration: 86400

