name: CICD

on:
    push:
        branches: [ deploy-to-ec2 ]
    pull_request:
        branches: [ deploy-to-ec2 ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source
          uses: actions/checkout@v3
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: '20'
        - name: Build with Maven
          run: mvn clean install -DskipTests
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build docker image
          run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rent-a-car .
        - name: Publish image to docker hub
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rent-a-car:latest
        - name: Set secrets as environment variables
          run: |
            echo "DB_URL=${{ secrets.DB_URL }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        - name: Use secrets in Docker
          run: |
            docker run --env-file .env your_docker_image

    deploy:
      needs: build
      runs-on: [aws-ec2]
      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Pull image from docker hub
          run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rent-a-car:latest
        - name: Delete old container
          run: docker rm -f rent-a-car
        - name: Run container
          run: docker run -d -p 8080:8080 --name rent-a-car ${{ secrets.DOCKERHUB_USERNAME }}/rent-a-car
